# Site settings
title: Where Ryan Puts His Notes
email: seh@example.com
description: > # this means to ignore newlines until "baseurl:"
  Well it's not really a blog...
baseurl: "http://ryan258.github.io/ryanleej" # the subpath of your site, e.g. /blog/
url: "http://ryan258.github.io/ryanleej" # the base hostname & protocol for your site
twitter_username: 
github_username:
facebook_pagename: 
ganalytics_UA: 

# Build settings
markdown: kramdown
